<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="TestFiles\**" />
		<Content Remove="TestFiles\**" />
		<EmbeddedResource Remove="TestFiles\**" />
		<None Remove="TestFiles\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.7" />
		<PackageReference Include="FreeRedis" Version="1.5.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\EasyLink.Storage\EasyLink.Storage.csproj" />
		<ProjectReference Include="..\..\src\EasyLink.Storage.Minio\EasyLink.Storage.Minio.csproj" />
		<ProjectReference Include="..\..\src\EasyLink.Storage.AliyunOSS\EasyLink.Storage.AliyunOSS.csproj" />
		<ProjectReference Include="..\..\src\EasyLink.Storage.TencentCOS\EasyLink.Storage.TencentCOS.csproj" />
		<ProjectReference Include="..\..\src\EasyLink.Storage.QiniuKodo\EasyLink.Storage.QiniuKodo.csproj" />
		<ProjectReference Include="..\..\src\EasyLink.Storage.HuaweiOBS\EasyLink.Storage.HuaweiOBS.csproj" />
		<ProjectReference Include="..\..\src\EasyLink.Storage.BaiduBOS\EasyLink.Storage.BaiduBOS.csproj" />
		<ProjectReference Include="..\..\src\EasyLink.Storage.CtyunOOS\EasyLink.Storage.CtyunOOS.csproj" />
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties appsettings_1json__JsonSchema="" />
		</VisualStudio>
	</ProjectExtensions>

</Project>
