<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageId>EasyLink.Storage.HuaweiOBS</PackageId>
    <AssemblyName>EasyLink.Storage.HuaweiOBS</AssemblyName>
    <RootNamespace>EasyLink.Storage.HuaweiOBS</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EasyLink.Storage\EasyLink.Storage.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\EasyLink.Storage\Services\HaweiOSSService.cs" Link="Services\HaweiOSSService.cs" />
    <Compile Include="..\EasyLink.Storage\Interface\Service\IHaweiOSSService.cs" Link="Interface\Service\IHaweiOSSService.cs" />
    <Compile Include="..\EasyLink.Storage\Models\Huawei\BucketStorageInfo.cs" Link="Models\Huawei\BucketStorageInfo.cs" />
    <Compile Include="..\EasyLink.Storage\SDK\HuaweiCloud\**\*.cs" LinkBase="SDK\HuaweiCloud" />
  </ItemGroup>
</Project>
